### ISSUE TITLE
Memory Error with Content Based Recommender

### ISSUE THREAD

**Issue by rhaegar453** [PacktPublishing/Hands-On-Recommendation-Systems-with-Python#3]
MemoryError                               Traceback (most recent call last)
<ipython-input-12-50f8658e68ee> in <module>()
      1 from sklearn.metrics.pairwise import linear_kernel
      2 # Compute the cosine similarity matrix
----> 3 cosine_sim=linear_kernel(tfidfmatrix, tfidfmatrix)

~/anaconda3/lib/python3.6/site-packages/sklearn/metrics/pairwise.py in linear_kernel(X, Y)
    740     """
    741     X, Y = check_pairwise_arrays(X, Y)
--> 742     return safe_sparse_dot(X, Y.T, dense_output=True)
    743 
    744 

~/anaconda3/lib/python3.6/site-packages/sklearn/utils/extmath.py in safe_sparse_dot(a, b, dense_output)
    135         ret = a * b
    136         if dense_output and hasattr(ret, "toarray"):
--> 137             ret = ret.toarray()
    138         return ret
    139     else:

~/anaconda3/lib/python3.6/site-packages/scipy/sparse/compressed.py in toarray(self, order, out)
    945         if out is None and order is None:
    946             order = self._swap('cf')[0]
--> 947         out = self._process_toarray_args(order, out)
    948         if not (out.flags.c_contiguous or out.flags.f_contiguous):
    949             raise ValueError('Output array must be C or F contiguous')

~/anaconda3/lib/python3.6/site-packages/scipy/sparse/base.py in _process_toarray_args(self, order, out)
   1182             return out
   1183         else:
-> 1184             return np.zeros(self.shape, dtype=self.dtype, order=order)
   1185 
   1186 

MemoryError:

**Comment by rhaegar453** [comment]
Tried running on colab with GPU runtime. The kernel kept restarting

**Comment by rounakbanik** [comment]
If you're running into a Memory Error, I suggest you use a smaller sample of the dataset. This will solve the memory problems and will be able to run on your local machine.
