### ISSUE TITLE
Chapter7 files

### ISSUE THREAD

**Issue by cryptocathy** [PacktPublishing/Hands-On-Recommendation-Systems-with-Python#6]
It says there are some files can be downloaded in Chapter 7 from your google drive but the URL seems invalid. Can I have the correct URL?

**Comment by sonam-packt** [comment]
Hi @cryptocathy,

Please use this link instead: https://drive.google.com/drive/folders/1pKPWbwacEnybJ_8buyuLWTkbh8CQ511s?usp=sharing.

Thanks!
